# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://livetune.github.io
date_format: "ordinal"
title: 打码
subtitle: "明日复明日，明天再打代码"
description: "连才荣的个人博客"
keywords: 码志, CaiRong lian, livetune
timezone: Asia/ShenZhen
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: CaiRong lian
organization: github.com/livetune
organization_url: https://github.com/livetune
github_username: livetune
location: ShenZhen, China
email: 243443394@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类
    
  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: livetune/livetune.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: livetune
    repo: blog-comments
    oauth:
        client_id: 6fc52e5d2f5589136f2b
        client_secret: 82b12f1f7ebe78ab8c16e07d89a22408159f05fe
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: livetune
    repo: blog-comments
    clientID: 6fc52e5d2f5589136f2b
    clientSecret: 82b12f1f7ebe78ab8c16e07d89a22408159f05fe
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
